### ISSUE TITLE
Funny pictures

### ISSUE THREAD

**Issue by rdehasseleer** [Lilyheart/yelp-camp#9]
Hey, i found your depot after seek to see the real contain of Colt Steele's bootcamp. I visited your  app, and there is some pictures weird. I prefer to warn you.

Anyway, thank for this depot.

**Comment by Lilyheart** [comment]
Thanks @romain-dehasseleer .  I think people get bored and have nothing better to do.  I go through and run a cleanup script every now and then.  Thanks for the heads up.  I run that soon.

**Comment by rdehasseleer** [comment]
You're welcome, it's normal. Indeed, they must think they are the kings now.... kings of kindergarten, of course.

**Comment by Lilyheart** [comment]
@romain-dehasseleer All cleaned up now.  

I find the ones that say something to the effect of `you've been hacked` funny...  hacked... because how? They created an account... and posted something?  um.......
